### ISSUE TITLE
low training accuracy 

### ISSUE THREAD

**Issue by RealRui** [euphoria0-0/Active-Client-Selection-for-Communication-efficient-Federated-Learning#5]
i use the benchmark :
 python src/main.py --dataset PartitionedCIFAR10 --model CNN -A 10 -K 100 --lr_local 0.1 -B 50 -R 1000
The training process is as follows：
>> ROUND 0
> pre-client selection 10/100
selected clients: [0, 16, 32, 42, 46, 52, 53, 66, 70, 99]
> Client Training: [===================>] 100% (10/10) Loss nan Acc 0.1935994909
> 10 Clients Training: Loss nan Acc 0.2345
> Client Testing: [===================>] 100% (100/100) Loss nan Acc 0.0000
> ALL Clients Testing: Loss nan Acc 0.0715

>> ROUND 1
> pre-client selection 10/100
selected clients: [12, 16, 26, 39, 43, 54, 60, 65, 68, 92]
> Client Training: [===================>] 100% (10/10) Loss nan Acc 0.0000
> 10 Clients Training: Loss nan Acc 0.0587
> Client Testing: [===================>] 100% (100/100) Loss nan Acc 0.0000
> ALL Clients Testing: Loss nan Acc 0.0715

>> ROUND 2
> pre-client selection 10/100
selected clients: [23, 49, 52, 60, 67, 71, 80, 82, 88, 97]
> Client Training: [===================>] 100% (10/10) Loss nan Acc 0.0000
> 10 Clients Training: Loss nan Acc 0.0500
> Client Testing: [===================>] 100% (100/100) Loss nan Acc 0.0000
> ALL Clients Testing: Loss nan Acc 0.0715

>> ROUND 3
> pre-client selection 10/100
selected clients: [2, 22, 24, 26, 27, 30, 66, 74, 75, 92]
> Client Training: [===================>] 100% (10/10) Loss nan Acc 0.0000
> 10 Clients Training: Loss nan Acc 0.0020
> Client Testing: [===================>] 100% (100/100) Loss nan Acc 0.0000
> ALL Clients Testing: Loss nan Acc 0.0715

>> ROUND 4
> pre-client selection 10/100
selected clients: [4, 8, 9, 18, 23, 24, 57, 69, 81, 84]
> Client Training: [===================>] 100% (10/10) Loss nan Acc 0.0000
> 10 Clients Training: Loss nan Acc 0.0212
> Client Testing: [===================>] 100% (100/100) Loss nan Acc 0.0000
> ALL Clients Testing: Loss nan Acc 0.0715

>> ROUND 5
> pre-client selection 10/100
selected clients: [17, 18, 22, 41, 49, 58, 61, 75, 79, 92]
> Client Training: [===================>] 100% (10/10) Loss nan Acc 0.0000
> 10 Clients Training: Loss nan Acc 0.0602
> Client Testing: [===================>] 100% (100/100) Loss nan Acc 0.0000
> ALL Clients Testing: Loss nan Acc 0.0715

>> ROUND 6
> pre-client selection 10/100
selected clients: [2, 7, 17, 27, 37, 43, 83, 95, 97, 98]
> Client Training: [===================>] 100% (10/10) Loss nan Acc 0.9097
> 10 Clients Training: Loss nan Acc 0.1458
> Client Testing: [===================>] 100% (100/100) Loss nan Acc 0.0000
> ALL Clients Testing: Loss nan Acc 0.0715

>> ROUND 7
> pre-client selection 10/100
selected clients: [1, 13, 20, 24, 35, 59, 69, 71, 72, 98]
> Client Training: [===================>] 100% (10/10) Loss nan Acc 0.9097
> 10 Clients Training: Loss nan Acc 0.2227
> Client Testing: [===================>] 100% (100/100) Loss nan Acc 0.0000
> ALL Clients Testing: Loss nan Acc 0.0715

>> ROUND 8
> pre-client selection 10/100
selected clients: [10, 18, 25, 28, 38, 40, 48, 50, 66, 90]
> Client Training: [===================>] 100% (10/10) Loss nan Acc 0.0000
> 10 Clients Training: Loss nan Acc 0.0702
> Client Testing: [===================>] 100% (100/100) Loss nan Acc 0.0000
> ALL Clients Testing: Loss nan Acc 0.0715

>> ROUND 9
> pre-client selection 10/100
selected clients: [18, 20, 39, 40, 44, 51, 68, 82, 84, 88]
> Client Training: [===================>] 100% (10/10) Loss nan Acc 0.0000
> 10 Clients Training: Loss nan Acc 0.0772
> Client Testing: [===================>] 100% (100/100) Loss nan Acc 0.0000
> ALL Clients Testing: Loss nan Acc 0.0715

>> ROUND 10
> pre-client selection 10/100
selected clients: [6, 10, 17, 53, 56, 58, 59, 70, 90, 91]
> Client Training: [===================>] 100% (10/10) Loss nan Acc 0.0000
> 10 Clients Training: Loss nan Acc 0.1173
> Client Testing: [===================>] 100% (100/100) Loss nan Acc 0.0000
> ALL Clients Testing: Loss nan Acc 0.0715

>> ROUND 11
> pre-client selection 10/100
selected clients: [0, 35, 36, 38, 39, 44, 45, 56, 84, 88]
> Client Training: [===================>] 100% (10/10) Loss nan Acc 0.0000
> 10 Clients Training: Loss nan Acc 0.1287
> Client Testing: [===================>] 100% (100/100) Loss nan Acc 0.0000
> ALL Clients Testing: Loss nan Acc 0.0715

>> ROUND 12
> pre-client selection 10/100
selected clients: [34, 43, 68, 70, 73, 75, 78, 81, 85, 90]
> Client Training: [===================>] 100% (10/10) Loss nan Acc 0.0000
> 10 Clients Training: Loss nan Acc 0.0263
> Client Testing: [===================>] 100% (100/100) Loss nan Acc 0.0000
> ALL Clients Testing: Loss nan Acc 0.0715

>> ROUND 13
> pre-client selection 10/100
selected clients: [4, 17, 18, 25, 28, 54, 62, 85, 92, 97]
> Client Training: [===================>] 100% (10/10) Loss nan Acc 0.0000
> 10 Clients Training: Loss nan Acc 0.0048
> Client Testing: [===================>] 100% (100/100) Loss nan Acc 0.0000
> ALL Clients Testing: Loss nan Acc 0.0715

>> ROUND 14
> pre-client selection 10/100
selected clients: [0, 11, 21, 36, 48, 55, 68, 80, 82, 83]
> Client Training: [===================>] 100% (10/10) Loss nan Acc 0.1935
> 10 Clients Training: Loss nan Acc 0.0923
> Client Testing: [===================>] 100% (100/100) Loss nan Acc 0.0000
> ALL Clients Testing: Loss nan Acc 0.0715

>> ROUND 15
> pre-client selection 10/100
selected clients: [1, 5, 18, 24, 29, 31, 32, 48, 74, 78]
> Client Training: [===================>] 100% (10/10) Loss nan Acc 0.0000
> 10 Clients Training: Loss nan Acc 0.0155
> Client Testing: [===================>] 100% (100/100) Loss nan Acc 0.0000
> ALL Clients Testing: Loss nan Acc 0.0715

>> ROUND 16
> pre-client selection 10/100
selected clients: [16, 22, 23, 37, 44, 45, 56, 69, 85, 87]
> Client Training: [===================>] 100% (10/10) Loss nan Acc 0.0000
> 10 Clients Training: Loss nan Acc 0.1274
> Client Testing: [===================>] 100% (100/100) Loss nan Acc 0.0000
> ALL Clients Testing: Loss nan Acc 0.0715

>> ROUND 17
> pre-client selection 10/100
selected clients: [9, 19, 24, 55, 56, 66, 70, 83, 85, 89]
> Client Training: [===================>] 100% (10/10) Loss nan Acc 0.1633
> 10 Clients Training: Loss nan Acc 0.1431
> Client Testing: [===================>] 100% (100/100) Loss nan Acc 0.0000
> ALL Clients Testing: Loss nan Acc 0.0715

>> ROUND 18
> pre-client selection 10/100
selected clients: [5, 23, 25, 36, 45, 48, 59, 69, 80, 87]
> Client Training: [===================>] 100% (10/10) Loss nan Acc 0.0000
> 10 Clients Training: Loss nan Acc 0.0000
> Client Testing: [===================>] 100% (100/100) Loss nan Acc 0.0000
> ALL Clients Testing: Loss nan Acc 0.0715

>> ROUND 19
> pre-client selection 10/100
selected clients: [2, 3, 4, 8, 17, 30, 38, 54, 82, 84]
> Client Training: [===================>] 100% (10/10) Loss nan Acc 0.0000
> 10 Clients Training: Loss nan Acc 0.0004
> Client Testing: [===================>] 100% (100/100) Loss nan Acc 0.0000
> ALL Clients Testing: Loss nan Acc 0.0715

>> ROUND 20
> pre-client selection 10/100
selected clients: [9, 25, 34, 49, 54, 64, 67, 69, 74, 77]
> Client Training: [===================>] 100% (10/10) Loss nan Acc 0.0000
> 10 Clients Training: Loss nan Acc 0.0008
> Client Testing: [===================>] 100% (100/100) Loss nan Acc 0.0000
> ALL Clients Testing: Loss nan Acc 0.0715

**Comment by euphoria0-0** [comment]
Could you change the learning rate of local (client)?

**Comment by euphoria0-0** [comment]
![image](https://user-images.githubusercontent.com/44519158/232643737-f294be9c-e469-470f-8380-8ee3a2579afa.png)
Try `--lr_local 0.001`.
