### ISSUE TITLE
Dataset: where Can I have access to this dataset

### ISSUE THREAD

**Issue by donwany** [euphoria0-0/Active-Client-Selection-for-Communication-efficient-Federated-Learning#7]
Here is the dataset in the code: RC_2017-11.bz2

**Comment by donwany** [comment]
You closed it without helping where I can get the data? Not professional.

**Comment by euphoria0-0** [comment]
Please check these references, very basic federated learning benchmark dataset as you know. I refered FedML for preprocessing.
Baumgartner, J. (2019). Reddit Comments Dumps. https://files.pushshift.io/reddit/comments/. Accessed: 2019-09-03.
And 
Jack Goetz et al., (2019), Active Federated Learning, https://arxiv.org/abs/1909.12641

**Comment by donwany** [comment]
> Please check these references, very basic federated learning benchmark dataset as you know. I refered FedML for preprocessing. Baumgartner, J. (2019). Reddit Comments Dumps. https://files.pushshift.io/reddit/comments/. Accessed: 2019-09-03. And Jack Goetz et al., (2019), Active Federated Learning, https://arxiv.org/abs/1909.12641

The first link requires username and password and not sure where it can be found

**Comment by euphoria0-0** [comment]
@donwany 
I think the website was modified after I downloaded, but you can get the alternative one from LEAF [code](https://github.com/TalwalkarLab/leaf/tree/master/data/reddit) [1].
[1] Sebastian Caldas et al., (2019) LEAF: A Benchmark for Federated Settings
